### ISSUE TITLE
Define invoicing usage scenario

### ISSUE THREAD

**Issue by fangpenlin** [balanced/billy#62]
With some inputs from a customer and the scenario of how invoice is processed in balanced, I have a better understanding of what invoicing should be.  For now, I am staring to describe usage scenarios here, improve the design gradually, and implement it when it looks good.

Some wanted features here:
- Emailing customer when a invoice is generated
- Generating invoices based on usage

Unlike what the most obvious usage scenario we mentioned in the previous development cycle, common hosting service providers can use billy to charge or payout a fixed amount to specific customers. However, not all of hosting service providers, or cloud service providers are charging customers in a fixed rate. Such as [Amazon Web Service](http://aws.amazon.com/), the price is basically determined by the usage. In this case, we want our customer to be able to charge customer based on metered usage. Another good example is Balanced itself, customer are charged based on transaction count. This is great, we can eat our own dog food at very first.

As we need to grab usage data from the user side, I think there are two obvious ways to do
- Pull from user server via HTTP periodically
- Push by user to billy

Still thinking pros and cons of these two approaches, however, maybe we can implement them all. But anyway, the data should contain
- Amount to charge
- Customers to charge
- Email addresses to notify (optional) 
- Title (optional) (to be displayed in email)
- Items (optional) (to be displayed in email)

I envision the data format of a invoice may look like this

``` yaml
amount: 100
customer: customer_guid
title: Foobar Super Cloud Service October Invoice
items:
    - name: Bandwidth usage
      count: 10
      unit: TB 
      amount: 20
    - name: Instance usage
      count: 200
      unit: hours
      amount: 80
notify_email:
    - foo@example.com
    - bar@example.com
```

On receiving these data from end of user, billy then generate corresponding invoice, send email to receivers and charge customers if it is necessary.

TODO:
- [x] design API calls 
- [x] ERD diagram
